# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XhdmiTools < Formula
  desc "XHDMI-Tools, e.g. for creating custom fonts and gamma/color maps"
  homepage "https://gitlab.com/chriz2600/xhdmi-tools"
  version "1.8.12"

  on_macos do
    if Hardware::CPU.arm?
      url "https://gitlab.com/chriz2600/xhdmi-tools/-/releases/1.8.12/downloads/xhdmi-tools_1.8.12_darwin_arm64.tar.gz"
      sha256 "4c709ccf1e95b71e767f8738461196f6d376d660de1921579e42d2c2c2e83e1f"

      def install
        bin.install "xhdmi-tools"
      end
    end
    if Hardware::CPU.intel?
      url "https://gitlab.com/chriz2600/xhdmi-tools/-/releases/1.8.12/downloads/xhdmi-tools_1.8.12_darwin_amd64.tar.gz"
      sha256 "d7743d79fd7db7520199865f0ba58b52b92c5d076dfa4a7a8939599fed3a027c"

      def install
        bin.install "xhdmi-tools"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://gitlab.com/chriz2600/xhdmi-tools/-/releases/1.8.12/downloads/xhdmi-tools_1.8.12_linux_arm.tar.gz"
      sha256 "2998d7c801aab4097f7a9c810a9e91fa420e71f077b02a1485f0342875ef1e6f"

      def install
        bin.install "xhdmi-tools"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://gitlab.com/chriz2600/xhdmi-tools/-/releases/1.8.12/downloads/xhdmi-tools_1.8.12_linux_arm64.tar.gz"
      sha256 "b3e66ebdc3c9e804bf37b08cc877bc9de40cf63e7166765c34b1cf7a6f7de0c1"

      def install
        bin.install "xhdmi-tools"
      end
    end
    if Hardware::CPU.intel?
      url "https://gitlab.com/chriz2600/xhdmi-tools/-/releases/1.8.12/downloads/xhdmi-tools_1.8.12_linux_amd64.tar.gz"
      sha256 "2902c8e8bed6b5fef8adc95914c338916e472dbc9cbfd616afc02f5a16c21be3"

      def install
        bin.install "xhdmi-tools"
      end
    end
  end
end
